In [1]:
import pandas as pd

df = pd.read_csv(r"D:\Proyectos\machine-learning\data\raw\exoplanets.csv")

print(df.shape)
print(df.head())

(6354, 11)
         pl_name     hostname  discoverymethod  disc_year    pl_orbper  \
0      HD 2039 b      HD 2039  Radial Velocity       2002  1120.000000
1      KOI-142 b      KOI-142          Transit       2013    10.916470
2      HAT-P-8 b      HAT-P-8          Transit       2008     3.076340
3        K2-43 b        K2-43          Transit       2016     3.471149
4  Kepler-1753 b  Kepler-1753          Transit       2021    16.004601

     pl_rade  pl_bmasse   pl_eqt  st_teff  st_rad  st_mass
0  12.700000  1999.1507   210.84   5945.0   1.190    1.230
1   3.438000     9.5000   758.00   5466.0   0.897    0.990
2  15.692600   406.8224  1713.00   6200.0   1.570    1.270
3   4.510000    18.5000   939.30   3840.6   0.542    0.571
4   2.226781     5.5900   583.00   5180.0   0.769    0.860

| Variable | Interpretación |
|---|---|
| `pl_name` | Nombre del planeta |
| `hostname` | Nombre de la estrella |
| `discoverymethod` | Método utilizado para descubrirlo |
| `disc_year` | Año del descubrimiento |
| `pl_orbper` | Período orbital |
| `pl_rade` | Radio del planeta |
| `pl_bmasse` | Masa del planeta |
| `pl_eqt` | Temperatura de equilibrio |
| `st_teff` | Temperatura efectiva de la estrella |
| `st_rad` | Radio de la estrella |
| `st_mass` | Masa de la estrella |

In [4]:
#La informacion de los datos que se tiene
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 6354 entries, 0 to 6353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          6354 non-null   str
 1   hostname         6354 non-null   str
 2   discoverymethod  6354 non-null   str
 3   disc_year        6354 non-null   int64
 4   pl_orbper        6009 non-null   float64
 5   pl_rade          6304 non-null   float64
 6   pl_bmasse        6323 non-null   float64
 7   pl_eqt           5825 non-null   float64
 8   st_teff          6056 non-null   float64
 9   st_rad           6032 non-null   float64
 10  st_mass          6345 non-null   float64
dtypes: float64(7), int64(1), str(3)
memory usage: 546.2 KB
None

In [21]:
#Contamos los valores vacios que existen en el dataset 
print(df.isnull().sum().sort_values(ascending=False))
print("="*50)
#Pequeña descripcion estadistica
print(df.describe().loc[["count","mean","std","min","max"]].T)

pl_eqt             529
pl_orbper          345
st_rad             322
st_teff            298
pl_rade             50
pl_bmasse           31
st_mass              9
discoverymethod      0
hostname             0
pl_name              0
disc_year            0
dtype: int64
==================================================
            count          mean           std          min           max
disc_year  6354.0   2017.268492  5.130195e+00  1992.000000  2.026000e+03
pl_orbper  6009.0  71243.583372  5.188337e+06     0.090706  4.020000e+08
pl_rade    6304.0      5.869737  5.429247e+00     0.309800  8.720587e+01
pl_bmasse  6323.0    407.375063  1.145822e+03     0.020000  9.534852e+03
pl_eqt     5825.0    835.177818  4.966238e+02     1.480000  7.777780e+03
st_teff    6056.0   5393.203327  1.726470e+03   415.000000  5.700000e+04
st_rad     6032.0      1.488896  3.859594e+00     0.011500  8.847500e+01
st_mass    6345.0      0.934674  3.868983e-01     0.009400  9.100000e+00

In [23]:
#Verificar si los nombres de los planetas no se dupliquen
duplicados = df["pl_name"].duplicated().sum()
if duplicados == 0:
    print ("No hay duplicados")
else: 
    print (f"existen {duplicados}")

No hay duplicados

In [29]:
print(df.nlargest(10,"pl_bmasse")[[
    "pl_name",
    "pl_bmasse",
    "pl_rade",
    "pl_eqt"
]])
print("="*50)
print(df.nlargest(10,"st_teff")[[
    "pl_name",
    "hostname",
    "st_teff",
    "st_rad",
    "st_mass"
]])
print("="*50)
print(df.nlargest(10, "pl_orbper")[[
    "pl_name",
    "pl_orbper",
    "pl_rade",
    "pl_bmasse",
    "pl_eqt"
]])

                         pl_name    pl_bmasse    pl_rade   pl_eqt
4956   2MASS J22501512+2325342 b  9534.852210  11.900000  1600.00
123                 CD-35 2722 b  9375.938007  17.373920  1800.00
5568                 Luhman 16 b  9344.155166  11.900000      NaN
4426                 HD 188641 b  9333.031172  11.900000   114.36
165         KMT-2018-BLG-0885L b  9217.023803  11.900000      NaN
5504  DENIS-P J082303.1-491201 b  9057.770000  11.900000      NaN
1307                  HD 26161 b  9045.396463  11.900000   110.98
4597                   HD 6860 b  8981.830782  11.900000  1196.06
4747   2MASS J11011926-7732383 b  8899.195396  11.900000  2677.00
5048                  TOI-5422 b  8899.195396   9.101692  1369.00
==================================================
                        pl_name                 hostname  st_teff  st_rad  \
1212                   NN Ser c                   NN Ser  57000.0     NaN
6243                   NN Ser d                   NN Ser  57000.0     NaN
1525            NSVS 14256825 b            NSVS 14256825  40000.0   0.188
334                    NY Vir b                   NY Vir  32780.0   0.151
2075                   NY Vir c                   NY Vir  32780.0   0.151
1333               Kepler-451 d  2MASS J19383260+4603591  29564.0   0.203
1354               Kepler-451 c  2MASS J19383260+4603591  29564.0   0.203
1711  2MASS J19383260+4603591 b  2MASS J19383260+4603591  29564.0   0.203
5374                V0391 Peg b                V0391 Peg  29300.0   0.230
1936                   KOI-55 c                   KOI-55  27730.0   0.203

      st_mass
1212    0.535
6243    0.535
1525    0.419
334     0.459
2075    0.459
1333    0.480
1354    0.480
1711    0.480
5374    0.500
1936    0.496
==================================================
                        pl_name     pl_orbper    pl_rade    pl_bmasse   pl_eqt
5172               COCONUTS-2 b  4.020000e+08  12.576476  2383.713052   493.00
6274           CFHTWIR-Oph 98 b  8.040000e+06  20.848704  2479.061575  1800.00
2267                   Oph 11 b  7.300000e+06  12.300000  4449.620000  2175.00
1760  VHS J125601.92-125723.9 b  5.800000e+06  13.674956  5085.254512  1194.00
4261                 b Cen AB b  1.790000e+06  12.400000  3464.329636      NaN
2122                  HR 8799 b  1.700000e+05  13.000000  2000.000000  1200.00
4942             HD 143811 AB b  1.170000e+05  15.692573  1938.753283  1042.00
4565              HIP 81208 C b  1.041000e+05  12.300000  4703.860424  2050.00
5638                HD 105618 c  7.711407e+04  11.900000  8419.592330    51.64
4451                 HD 62364 c  7.483995e+04  12.000000  7923.462187    58.70

In [31]:
df.groupby("discoverymethod").agg(
    total = ("pl_name","count"),
    faltantes_eqt = ("pl_eqt", lambda x : x.isna().sum()),
    faltantes_mass= ("pl_bmasse", lambda x : x.isna().sum())

)

                               total  faltantes_eqt  faltantes_mass
discoverymethod
Astrometry                         6              3               0
Disk Kinematics                    1              0               0
Eclipse Timing Variations         17             10               0
Imaging                           98              8               3
Microlensing                     283            276               0
Orbital Brightness Modulation      9              6               3
Pulsar Timing                      8              8               0
Pulsation Timing Variations        2              1               0
Radial Velocity                 1200             44               1
Transit                         4688            166              23
Transit Timing Variations         42              7               1

In [38]:
# total = df["pl_name"].count()
# df.groupby("disc_year").agg(
#     planetas_descubiertos = ("pl_name","count"),
#     porcentaje = ("pl_name", lambda x : len(x)/total * 100) 
# ).sort_values(by="porcentaje",ascending=False)

In [40]:

df.select_dtypes(include="number").corr(method="spearman")

,disc_year,pl_orbper,pl_rade,pl_bmasse,pl_eqt,st_teff,st_rad,st_mass
disc_year,1.000000,-0.143930,-0.019178,-0.025899,0.048779,-0.123174,-0.135569,-0.163697
pl_orbper,-0.143930,1.000000,0.303750,0.340923,-0.783635,0.040185,0.196191,0.148471
pl_rade,-0.019178,0.303750,1.000000,0.929840,-0.062168,0.194757,0.422140,0.310991
pl_bmasse,-0.025899,0.340923,0.929840,1.000000,-0.107269,0.147999,0.389540,0.282591
pl_eqt,0.048779,-0.783635,-0.062168,-0.107269,1.000000,0.360965,0.313758,0.327680
st_teff,-0.123174,0.040185,0.194757,0.147999,0.360965,1.000000,0.732274,0.782453
st_rad,-0.135569,0.196191,0.422140,0.389540,0.313758,0.732274,1.000000,0.929932
st_mass,-0.163697,0.148471,0.310991,0.282591,0.327680,0.782453,0.929932,1.000000